# Generated by Django 5.1.6 on 2025-02-26 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('cnh', models.CharField(max_length=11, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cd_control.firm')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.CharField(max_length=7, unique=True)),
                ('cart_plate', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cd_control.firm')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cd_control.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='EntryExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('materia_prima', 'Recebimento de Matéria-Prima'), ('carregamento', 'Carregamento'), ('residuos', 'Retirada de Resíduos'), ('leite', 'Entrada de Leite'), ('visitantes', 'Entrada de Visitantes/Terceiros')], max_length=20)),
                ('entry_datetime', models.DateTimeField(auto_now_add=True)),
                ('start_unload_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_unload_datetime', models.DateTimeField(blank=True, null=True)),
                ('exit_datetime', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pallets_quantity', models.IntegerField(blank=True, null=True)),
                ('origin_route', models.CharField(blank=True, max_length=255, null=True)),
                ('authorized_by', models.CharField(blank=True, max_length=100, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cd_control.driver')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cd_control.firm')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cd_control.producttype')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cd_control.vehicle')),
            ],
        ),
    ]
